import Link from 'next/link';
import { Inter } from 'next/font/google';
import { Upload, LayoutDashboard, FileText, Lock, Star, Check, ArrowRight, Rss, Layers, BarChart3, Users, Database, CreditCard, ShieldCheck } from 'lucide-react';
import { clsx } from 'clsx'; // Only clsx needed here, not tailwind-merge for static classes

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Client Proof Pack Builder — Prove ROI. Retain Clients.',
  description: 'The Client Proof Pack Builder allows small digital agencies to rapidly transform disparate campaign results into structured, client-ready proof packs, ensuring clarity and justification for their services.',
};

const FEATURES = [
  {
    icon: Upload,
    name: "Effortless Data Intake",
    description: "Stop manual data wrangling. Quickly capture campaign metrics and client details, turning messy inputs into structured proof pack drafts ready for action.",
    bg: "bg-indigo-100",
    text: "text-indigo-600",
  },
  {
    icon: LayoutDashboard,
    name: "Centralized Workflow Dashboard",
    description: "Gain clarity on every client's reporting status. Prioritize high-value proof packs and see what needs your attention now, ensuring no deadline is missed.",
    bg: "bg-emerald-100",
    text: "text-emerald-600",
  },
  {
    icon: FileText,
    name: "Client-Ready Export & Delivery",
    description: "Produce polished, exportable proof packs that clearly demonstrate ROI. Eliminate manual cleanup and present professional reports that justify your retainer.",
    bg: "bg-orange-100",
    text: "text-orange-600",
  },
];

const HOW_IT_WORKS_STEPS = [
  {
    step: 1,
    title: "Ingest Campaign Data",
    description: "Easily input client details, campaign metrics, and reporting periods to create a new Proof Pack draft.",
    iconBg: "bg-indigo-100",
    iconText: "text-indigo-600",
  },
  {
    step: 2,
    title: "Manage & Prioritize",
    description: "Use the central dashboard to track pack statuses, review drafts, and prioritize what's 'Ready for Export'.",
    iconBg: "bg-emerald-100",
    iconText: "text-emerald-600",
  },
  {
    step: 3,
    title: "Export & Deliver",
    description: "Generate professional, branded proof packs as PDFs or web links, instantly showcasing client ROI.",
    iconBg: "bg-orange-100",
    iconText: "text-orange-600",
  },
];

const PRICING_TIERS = [
  {
    name: "Starter",
    price: "₹0",
    interval: "/mo",
    features: [
      "1 Active Client",
      "2 Proof Packs/mo",
      "Standard Exports",
      "Basic Support",
    ],
    buttonText: "Get Started Free",
    buttonLink: "/dashboard",
    highlight: false,
  },
  {
    name: "Agency",
    price: "₹3,999",
    interval: "/mo",
    features: [
      "Unlimited Clients",
      "Unlimited Proof Packs",
      "Advanced Exports",
      "Unlock Full Roadmap",
    ],
    buttonText: "Start Agency Plan",
    buttonLink: "/dashboard", // Links to dashboard, pricing handled internally in the app
    highlight: true,
  },
  {
    name: "Pro",
    price: "Custom",
    interval: "",
    features: [
      "Everything in Agency",
      "Dedicated Support",
      "Custom Integrations",
      "Enhanced Security & SLA",
    ],
    buttonText: "Contact Sales",
    buttonLink: "mailto:sales@clientproofpackbuilder.com",
    highlight: false,
  },
];

const TESTIMONIALS = [
  {
    quote: "Client Proof Pack Builder has cut our reporting time by 70%. We used to dread month-end reports, but now we can generate professional proof packs in minutes, which has made client renewals so much smoother.",
    name: "Sarah L.",
    role: "Founder, Stellar Marketing",
    rating: 5,
  },
  {
    quote: "Finally, a tool built for agencies! The dashboard gives us instant clarity on all our client reports, and the export feature delivers exactly what clients need to see their ROI. It's transformed how we justify our value.",
    name: "Mark P.",
    role: "Account Director, Growth Metrics",
    rating: 5,
  },
  {
    quote: "We landed two new clients just by showing them our proof packs generated by this platform. The ability to quickly visualize campaign success has become a huge differentiator for us.",
    name: "Emily R.",
    role: "Lead Strategist, Digital Edge Solutions",
    rating: 5,
  },
];

const DEFERRED_ROADMAP_FEATURES = [
  { icon: Rss, name: "Intake Automation", value: "Auto-pull data from ad platforms.", tier: "Agency" },
  { icon: Layers, name: "Reporting Automation", value: "Scheduled report generation & delivery.", tier: "Agency" },
  { icon: BarChart3, name: "AI Analysis & Insights", value: "AI-driven performance summaries.", tier: "Agency" },
  { icon: Users, name: "Team Roles & Permissions", value: "Secure collaboration for your team.", tier: "Agency" },
  { icon: Database, name: "Real Database Persistence", value: "Secure, scalable data storage.", tier: "Pro" },
  { icon: CreditCard, name: "Billing & Entitlements", value: "Manage subscriptions and features.", tier: "Pro" },
  { icon: ShieldCheck, name: "Enhanced Security", value: "Advanced security protocols & audits.", tier: "Pro" },
];

export default function LandingPage() {
  return (
    <div className={inter.className}>
      {/* Navbar */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-white/90 backdrop-blur-sm border-b border-zinc-100">
        <div className="mx-auto max-w-7xl h-16 flex items-center justify-between px-6">
          <Link href="/" className="flex items-center space-x-2">
            <div className="w-8 h-8 bg-indigo-600 rounded-lg flex items-center justify-center text-white font-bold text-lg">CP</div>
            <span className="font-bold text-zinc-900 text-xl tracking-tight">Client Proof Pack Builder</span>
          </Link>
          <div className="flex items-center space-x-4">
            <Link href="#features" className="text-zinc-600 hover:text-zinc-900 transition-colors">Features</Link>
            <Link href="#pricing" className="text-zinc-600 hover:text-zinc-900 transition-colors">Pricing</Link>
            <Link href="/dashboard" className="bg-zinc-900 text-white rounded-lg px-4 py-2 hover:bg-zinc-700 transition-colors flex items-center gap-2">
              Open Dashboard <ArrowRight className="h-4 w-4" />
            </Link>
          </div>
        </div>
      </nav>

      <main>
        {/* Hero Section */}
        <section className="bg-gradient-to-br from-zinc-900 via-zinc-800 to-zinc-900 text-white min-h-screen flex flex-col items-center justify-center text-center px-6 pt-24">
          <span className="inline-flex items-center rounded-full bg-indigo-500/20 px-3 py-1 text-sm font-medium text-indigo-300 ring-1 ring-inset ring-indigo-500/20">
            AI-Powered Client Proof Packs
          </span>
          <h1 className="font-black text-5xl md:text-7xl tracking-tight leading-none mt-6 max-w-4xl">
            Transform Campaign Data. Prove Client ROI.
          </h1>
          <p className="text-zinc-400 text-xl mt-4 max-w-3xl">
            Client Proof Pack Builder helps small digital agencies rapidly convert scattered results into structured, compelling proof packs that justify retainers and drive renewals.
          </p>
          <div className="flex gap-4 mt-8">
            <Link href="/dashboard" className="bg-white text-zinc-900 font-bold rounded-xl px-8 py-4 shadow-lg hover:shadow-xl transition-all flex items-center gap-2">
              Start Free Today <ArrowRight className="h-5 w-5" />
            </Link>
            <Link href="/dashboard" className="border border-zinc-600 text-zinc-300 rounded-xl px-8 py-4 hover:bg-zinc-800 transition-colors flex items-center gap-2">
              See It Live <ArrowRight className="h-5 w-5" />
            </Link>
          </div>

          {/* Hero Visual - CSS-only UI mockup */}
          <div className="relative rounded-2xl bg-zinc-800/50 border border-zinc-700 p-6 max-w-4xl mx-auto mt-16 w-full shadow-2xl overflow-hidden">
            <div className="absolute top-4 left-4 flex space-x-2">
              <div className="w-3 h-3 bg-red-500 rounded-full"></div>
              <div className="w-3 h-3 bg-yellow-400 rounded-full"></div>
              <div className="w-3 h-3 bg-green-500 rounded-full"></div>
            </div>
            <div className="bg-zinc-700 h-8 rounded-md flex items-center px-4 mt-1">
              <div className="w-3/4 h-3 bg-zinc-600 rounded-sm"></div>
              <div className="w-1/4 h-3 bg-zinc-600 rounded-sm ml-auto"></div>
            </div>

            <div className="mt-6 flex gap-6">
              {/* Sidebar simulation */}
              <div className="w-1/4 bg-zinc-700/50 rounded-lg p-4 space-y-4 hidden md:block">
                <div className="h-4 w-3/4 bg-zinc-600 rounded-sm"></div>
                <div className="h-4 w-2/3 bg-zinc-600 rounded-sm"></div>
                <div className="h-4 w-4/5 bg-zinc-600 rounded-sm